Custom Lab/CustomLab/DogAdoption.Website/Models/Dog.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogAdoption.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dog()
        {
            this.Adoptions = new HashSet<Adoption>();
        }
    
        public int DogId { get; set; }
        public string Name { get; set; }
        public bool isAvailable { get; set; }
        public string Breed { get; set; }
        public int Age { get; set; }
        public string Comments { get; set; }
        public string DogImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adoption> Adoptions { get; set; }
    }
}

Custom Lab/CustomLab/DogAdoption.Website/Controllers/DogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using DogAdoption.Website.Models;
using DogAdoption.Website.ViewModels;
using NLog;
using PagedList;

namespace DogAdoption.Website.Controllers
{
    public class DogsController : Controller
    {
        private DogAdoptionEntities1 db = new DogAdoptionEntities1();
        private Logger logger = LogManager.GetCurrentClassLogger();


        public bool ValidateImage(string name, HttpPostedFileBase file)
        {
            if (file == null)
            {
                ModelState.AddModelError(name, "Please select a file");
                return false;
            }

            if (file.ContentLength <= 0)
            {
                ModelState.AddModelError(name, "File size was zero");
                return false;
            }

            if (file.ContentLength >= Constants.MAX_UPLOAD_FILE_SIZE)
            {
                ModelState.AddModelError(name, "File size was to big");
                return false;
            }

            string fileExtension = Path.GetExtension(file.FileName).ToLower();
            if (!Constants.ALLOWED_IMAGE_EXTENSIONS.Contains(fileExtension))
            {
                ModelState.AddModelError(name, $"File extension {fileExtension} not allowed");
                return false;
            }

            return true;
        }

        private void UploadDogImage(Dog dog, HttpPostedFileBase file)
        {
            WebImage img = new WebImage(file.InputStream);
            if (img.Width > 350 || img.Height > 600)
            {
                img.Resize(350, 600);
            }

            string fileName = file.FileName.ToLower();
            img.Save(Constants.DOGS_FOLDER_PATH + fileName);

            img.Resize(100, 100);
            img.Save(Constants.DOGS_FOLDER_PATH + Constants.THUMBNAILS_FOLDER + fileName);

            dog.DogImage = fileName;
        }
        // GET: Dogs
        [AllowAnonymous]
        public ActionResult Index(
            string search,
            string sortBy,
            int? page,
            int? itemsPerPage)
        {
            IQueryable<Dog> dog =
                from d in db.Dogs
                orderby d.DogId, d.Name
                select d;

            dog = dog.Where(m => m.isAvailable == true);

            if (!String.IsNullOrWhiteSpace(search))
            {
                dog = dog.Where(
                       m => m.Name.Contains(search) ||
                       m.DogId.ToString().Contains(search)
                    );
            }

            switch (sortBy)
            {
                default:
                case "dogNumber":
                    dog = dog.OrderBy(m => m.DogId);
                    break;
                case "dogName":
                    dog = dog.OrderBy(m => m.Name);
                    break;
            }

            var model = new DogSearchResults()
            {
                Search = search,
                SortBy = sortBy,
                Dogs = dog.ToPagedList(page ?? 1, itemsPerPage ?? 5)
            };

            return View("Index", model);
        }

        // GET: Dogs/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dog dog = db.Dogs.Find(id);
            if (dog == null)
            {
                return HttpNotFound();
            }
            logger.Info($"{User.Identity.Name} viewed {dog.Name}");
            return View(dog);
        }

        // GET: Dogs/Create
        [Authorize(Roles = "Admin, Manager")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Dogs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "DogId,Name,isAvailable,Breed,Age,Comments,DogImage")]
        Dog dog,
            HttpPostedFileBase imageUpload)
        {
            try
            { 
                if (imageUpload != null &&
                   ValidateImage("DogImage", imageUpload))
                {
                    UploadDogImage(dog, imageUpload);
                }

                if (ModelState.IsValid)
                {
                    dog.isAvailable = true;
                    db.Dogs.Add(dog);
                    logger.Info($"{User.Identity.Name} created {dog.Name}");
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            catch (Exception ex)
            {
                logger.Error(ex, $"{User.Identity.Name} had an error creating {dog.Name}");
                ModelState.AddModelError("CustomerId", ex);
            }
            return View(dog);
        }

        // GET: Dogs/Edit/5
        [Authorize(Roles = "Admin, Manager")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dog dog = db.Dogs.Find(id);
            if (dog == null)
            {
                return HttpNotFound();
            }
            return View(dog);
        }

        // POST: Dogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Manager")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "DogId,Name,isAvailable,Breed,Age,Comments,DogImage")]
        Dog dog,
           HttpPostedFileBase imageUpload)
        {
            try
            {
                if (imageUpload != null &&
                   ValidateImage("DogImage", imageUpload))
                {
                    UploadDogImage(dog, imageUpload);
                }

                if (ModelState.IsValid)
                {
                    db.Entry(dog).State = EntityState.Modified;
                    logger.Info($"{User.Identity.Name} modified {dog.Name}");
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                logger.Error(ex, $"{User.Identity.Name} had an error editing {dog.Name}");
                ModelState.AddModelError("CustomerId", ex);
            }
            return View(dog);
        }

        // GET: Dogs/Delete/5
        [Authorize(Roles = "Admin, Manager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dog dog = db.Dogs.Find(id);
            if (dog == null)
            {
                return HttpNotFound();
            }
            return View(dog);
        }

        // POST: Dogs/Delete/5
        [Authorize(Roles = "Admin, Manager")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            { 
                Dog dog = db.Dogs.Find(id);
                db.Dogs.Remove(dog);
                logger.Info($"{User.Identity.Name} deleted {dog.Name}");
                db.SaveChanges();
            }
            catch (Exception ex)
            {
                logger.Error(ex, $"{User.Identity.Name} had an error deleting {db.Dogs.Find(id).Name}");
                ModelState.AddModelError("CustomerId", ex);
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Custom Lab/CustomLab/DogAdoption.Website/Views/Dogs/Create.cshtml
@model DogAdoption.Website.Models.Dog

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Dogs", FormMethod.Post,
    new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Dog</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <span>Available</span>
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.isAvailable)
                @Html.ValidationMessageFor(model => model.isAvailable, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Breed, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Breed, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Breed, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <span>Image</span>
        <div class="col-md-10">
            @Html.EditorFor(model => model.DogImage, new { htmlAttributes = new { @class = "form-control", list = "dog_images", size = 20 } })
            <input type="file" name="imageUpload" class="form-control-file" id="dogProtrait" />
            @Html.ValidationMessageFor(model => model.DogImage, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>
    $("#dogProtrait").change(function (e) {
        $("#DogImage").val(this.files[0].name)})
</script>

Custom Lab/CustomLab/DogAdoption.Website/Views/Dogs/Delete.cshtml
@model DogAdoption.Website.Models.Dog

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Dog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            <span>Available</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.isAvailable)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Breed)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Breed)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comments)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comments)
        </dd>

        <dt>
            <span>Image</span>
        </dt>

        <dd>
            @if (!string.IsNullOrWhiteSpace(Model.DogImage))
            {
                string url = Url.Content(
                   Constants.DOGS_FOLDER_PATH +
                   Model.DogImage);
                <img src="@url" />
            }
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Custom Lab/CustomLab/DogAdoption.Website/Views/Dogs/Details.cshtml
@model DogAdoption.Website.Models.Dog

@{
    ViewBag.Title = "Details";

    bool isManager =
      Request.IsAuthenticated &&
      (User.IsInRole("Admin") || User.IsInRole("Manager"));

}

<h2>Details</h2>

<div>
    <h4>Dog</h4>
    <hr />
    <dl class="dl-horizontal" style="display: flex; flex-direction: row; justify-content: space-around; margin: 0 auto; width: 60%; font-size: 1.5em;">
        <div>
            <dt>
                <span>Image</span>
            </dt>

            <dd>
                @if (!string.IsNullOrWhiteSpace(Model.DogImage))
                {
                    string url = Url.Content(
                       Constants.DOGS_FOLDER_PATH +
                       Model.DogImage);
                    <img src="@url" />
                }
            </dd>

        </div>
        <div style="padding-top: 10px;">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                <span>Available</span>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.isAvailable)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Breed)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Breed)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Age)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Age)
            </dd>
            @if (!string.IsNullOrWhiteSpace(Model.Comments))
            {
                <dt>
                    @Html.DisplayNameFor(model => model.Comments)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Comments)
                </dd>
            }
        </div>

    </dl>
</div>
<p>
    @if (isManager)
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.DogId }) 
        <span>|</span>
}
    @Html.ActionLink("Back to List", "Index")
</p>

Custom Lab/CustomLab/DogAdoption.Website/Views/Dogs/Edit.cshtml
@model DogAdoption.Website.Models.Dog

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Dogs", FormMethod.Post,
    new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Dog</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DogId)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span>Available</span>
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.isAvailable)
                    @Html.ValidationMessageFor(model => model.isAvailable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Breed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Breed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Breed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comments, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comments, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span>Image</span>
            <div class="col-md-10">
                @Html.EditorFor(model => model.DogImage, new { htmlAttributes = new { @class = "form-control", list = "images" } })
                <input type="file" name="imageUpload" class="form-control-file" />
                @Html.ValidationMessageFor(model => model.DogImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Custom Lab/CustomLab/DogAdoption.Website/Views/Dogs/Index.cshtml
@model DogAdoption.Website.ViewModels.DogSearchResults

@using PagedList.Mvc
@{
    ViewBag.Title = "Index";

    bool isManager =
      Request.IsAuthenticated &&
      (User.IsInRole("Admin") || User.IsInRole("Manager"));
}

<h2>Index</h2>

@using (Html.BeginForm("Index", "Dogs", FormMethod.Get,
    new { enctype = "multipart/form-data" }))
{

    var sortByArray = new SelectListItem[]
    {
new SelectListItem {Value = "dogNumber", Text = "Dog Number"},
new SelectListItem {Value = "dogName", Text = "Dog Name"}
    };

    <div class="mb-3">
        @Html.EditorFor(m => m.Search, new { htmlAttributes = new { placeholder = "search" } })
        @Html.DropDownListFor(m => m.SortBy, sortByArray)

        <input class="btn btn-primary" type="submit" value="Apply" />
    </div>
}

@if (isManager)
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}

<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            <span>Image</span>
        </th>
        <th>
            Breed
        </th>
        <th>
            Age
        </th>
        <th>
            <span>Available</span>
        </th>
        <th>
            Comments
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model.Dogs)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @if (!string.IsNullOrWhiteSpace(item.DogImage))
            {
                string url = Url.Content(
                   Constants.DOGS_FOLDER_PATH +
                   Constants.THUMBNAILS_FOLDER +
                   item.DogImage);
                <img src="@url" />
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Breed)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Age)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.isAvailable)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Comments)
        </td>
        <td>
            @if (!string.IsNullOrWhiteSpace(item.DogImage))
            {
                string url = Url.Content(
                   Constants.DOGS_FOLDER_PATH +
                   Constants.THUMBNAILS_FOLDER +
                   item.DogImage);
                <img src="@url" />
            }
        </td>
        <td>
            @if (isManager)
            {
                @Html.ActionLink("Edit", "Edit", new { id = item.DogId })
                <span>|</span>
            }
            @Html.ActionLink("Details", "Details", new { id = item.DogId })
            @if (isManager)
            {
                <span>|</span>
                @Html.ActionLink("Delete", "Delete", new { id = item.DogId })
            }
        </td>
    </tr>
    }

</table>
<div>
    @Html.PagedListPager(
    Model.Dogs,
    page => Url.Action("Index", new
    {
        search = Model.Search,
        sortBy = Model.SortBy,
        page = page,
        itemsPerPage = Model.Dogs.PageSize,
    }),
    new PagedListRenderOptions
    {
        Display = PagedListDisplayMode.IfNeeded,
        DisplayPageCountAndCurrentLocation = true,
        DisplayEllipsesWhenNotShowingAllPageNumbers = true,
        MaximumPageNumbersToDisplay = 5,
        PageCountAndCurrentLocationFormat = "Page {0} of {1}"
    })

</div>

@section scripts
{
    <script>
        $(".pagination > li").addClass("page-item");
        $(".pagination > li > a").addClass("page-link");
    </script>
}