Custom Lab/CustomLab/DogAdoption.Website/Models/Adoption.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogAdoption.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adoption
    {
        public int CustomerId { get; set; }
        public int DogId { get; set; }
        public System.DateTime AdoptionDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Dog Dog { get; set; }
    }
}

Custom Lab/CustomLab/DogAdoption.Website/Controllers/AdoptionsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DogAdoption.Website.Models;
using DogAdoption.Website.ViewModels;
using NLog;
using PagedList;

namespace DogAdoption.Website.Controllers
{
    public class AdoptionsController : Controller
    {
        private DogAdoptionEntities1 db = new DogAdoptionEntities1();
        private Logger logger = LogManager.GetCurrentClassLogger();

        // GET: Adoptions
        [AllowAnonymous]
        public ActionResult Index(
            string search,
            string sortBy,
            int? page,
            int? itemsPerPage)
        {
            IQueryable<Adoption> adopt =
                from a in db.Adoptions
                join c in db.Customers on a.CustomerId equals c.CustomerId
                join d in db.Dogs on a.DogId equals d.DogId
                orderby a.AdoptionDate
                select a;

            if (!String.IsNullOrWhiteSpace(search))
            {
                adopt = adopt.Where(
                       m => m.Customer.Name.Contains(search) ||
                       m.Dog.Name.Contains(search) ||
                       m.DogId.ToString().Contains(search) ||
                       m.CustomerId.ToString().Contains(search)
                    );
            }

            switch (sortBy)
            {
                default:
                case "date":
                    adopt = adopt.OrderBy(m => m.AdoptionDate);
                    break;
                case "dogName":
                    adopt = adopt.OrderBy(m => m.Dog.Name);
                    break;
                case "customerName":
                    adopt = adopt.OrderBy(m => m.Customer.Name);
                    break;
            }

            var model = new AdoptionSearchResults()
            {
                Search = search,
                SortBy = sortBy,
                Adoptions = adopt.ToPagedList(page ?? 1, itemsPerPage ?? 5)
            };

            return View("Index", model);
        }

        // GET: Adoptions/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id, int? dog)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adoption adoption = db.Adoptions.Find(id, dog);
            if (adoption == null)
            {
                return HttpNotFound();
            }
            logger.Info($"{User.Identity.Name} viewed the adoption of {adoption.Dog.Name}");
            return View(adoption);
        }

        // GET: Adoptions/Create
        [Authorize(Roles = "Admin, Manager, Counselor")]
        public ActionResult Create()
        {
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Name");
            ViewBag.DogId = new SelectList(db.Dogs, "DogId", "Name");
            return View();
        }

        // POST: Adoptions/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Manager, Counselor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CustomerId,DogId,AdoptionDate")] Adoption adoption)
        {
            try
            { 
                if (ModelState.IsValid)
                {
                    Dog dog = db.Dogs.Find(adoption.DogId);

                    if(dog.isAvailable == true)
                    {
                        dog.isAvailable = false;
                        db.Entry(dog).State = EntityState.Modified;
                        adoption.AdoptionDate = DateTime.Today;
                        db.Adoptions.Add(adoption);
                        logger.Info($"{User.Identity.Name} created the adoption of {adoption.Dog.Name}");
                        db.SaveChanges();
                        return RedirectToAction("Index");
                    }
                }

                ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Name", adoption.CustomerId);
                ViewBag.DogId = new SelectList(db.Dogs, "DogId", "Name", adoption.DogId);
            }
            catch (Exception ex)
            {
                logger.Error(ex, $"{User.Identity.Name} had an error creating the adoption of {adoption.Dog.Name}");
                ModelState.AddModelError("CustomerId", ex);
            }
            return View(adoption);
        }

        // GET: Adoptions/Edit/5
        [Authorize(Roles = "Admin, Manager, Counselor")]
        public ActionResult Edit(int? id, int? dog)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adoption adoption = db.Adoptions.Find(id, dog);
            if (adoption == null)
            {
                return HttpNotFound();
            }
            ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Name", adoption.CustomerId);
            ViewBag.DogId = new SelectList(db.Dogs, "DogId", "Name", adoption.DogId);
            return View(adoption);
        }

        // POST: Adoptions/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Manager, Counselor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CustomerId,DogId,AdoptionDate")] Adoption adoption)
        {
            try
            { 
                if (ModelState.IsValid)
                {
                    db.Entry(adoption).State = EntityState.Modified;
                    logger.Info($"{User.Identity.Name} modified the adoption of {adoption.Dog.Name}");
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.CustomerId = new SelectList(db.Customers, "CustomerId", "Name", adoption.CustomerId);
                ViewBag.DogId = new SelectList(db.Dogs, "DogId", "Name", adoption.DogId);
            }
            catch (Exception ex)
            {
                logger.Error(ex, $"{User.Identity.Name} had an error editing the adoption of {adoption.Dog.Name}");
                ModelState.AddModelError("CustomerId", ex);
            }
            return View(adoption);
        }

        [Authorize(Roles = "Admin, Manager")]
        // GET: Adoptions/Delete/5
        public ActionResult Delete(int? id, int? dog)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Adoption adoption = db.Adoptions.Find(id, dog);
            if (adoption == null)
            {
                return HttpNotFound();
            }
            return View(adoption);
        }

        // POST: Adoptions/Delete/5
        [Authorize(Roles = "Admin, Manager")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, int dog)
        {
            try
            { 
                Adoption adoption = db.Adoptions.Find(id, dog);
                Dog _dog = db.Dogs.Find(adoption.DogId);
                _dog.isAvailable = true;
                db.Entry(_dog).State = EntityState.Modified;
                db.Adoptions.Remove(adoption);
                logger.Info($"{User.Identity.Name} removed the adoption of {adoption.Dog.Name}");
                db.SaveChanges();
            }
            catch (Exception ex)
            {
                logger.Error(ex, $"{User.Identity.Name} had an error deleting the adoption of {db.Adoptions.Find(id, dog).Dog.Name}");
                ModelState.AddModelError("CustomerId", ex);
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Custom Lab/CustomLab/DogAdoption.Website/Views/Adoptions/Create.cshtml
@model DogAdoption.Website.Models.Adoption

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Adoption</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <span>Customer</span>
            <div class="col-md-10">
                @Html.DropDownList("CustomerId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CustomerId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <span>Dog</span>
            <div class="col-md-10">
                @Html.DropDownList("DogId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DogId, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            <span>Adoption Date</span>
            <div class="col-md-10">
                @Html.HiddenFor(model => model.AdoptionDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdoptionDate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Custom Lab/CustomLab/DogAdoption.Website/Views/Adoptions/Delete.cshtml
@model DogAdoption.Website.Models.Adoption

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Adoption</h4>
    <hr />
    <dl class="dl-horizontal">
        <div style="margin: 0 auto; width: 20%; font-size: 2em; display: flex; flex-direction: column; justify-content: center;">
            <dt>
                <span>Adoption Date</span>
            </dt>
            <dd style="padding-left: 15px;">
                @Html.DisplayFor(model => model.AdoptionDate)
            </dd>

        </div>
        <div style="display: flex; flex-direction: row; justify-content: space-between; margin: 0 auto; width: 60%; padding-top: 60px;">
            <div>
                <dt>
                    <span>Customer</span>
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Customer.Name)
                    @if (!string.IsNullOrWhiteSpace(Model.Customer.CustomerImage))
                    {
                        string url = Url.Content(
                           Constants.CUSTOMERS_FOLDER_PATH +
                           Model.Customer.CustomerImage);
                        <img src="@url" style="display: flex; justify-content: center;" />
                    }
                </dd>
            </div>
            <div>
                <dt>
                    <span>Dog</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Dog.Name)
                    @if (!string.IsNullOrWhiteSpace(Model.Dog.DogImage))
                    {
                        string url = Url.Content(
                           Constants.DOGS_FOLDER_PATH +
                           Model.Dog.DogImage);
                        <img src="@url" style="display: flex; justify-content: center;" />
                    }
                </dd>
            </div>
        </div>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Custom Lab/CustomLab/DogAdoption.Website/Views/Adoptions/Details.cshtml
@model DogAdoption.Website.Models.Adoption

@{
    ViewBag.Title = "Details";


    bool isManager =
      Request.IsAuthenticated &&
      (User.IsInRole("Admin") || User.IsInRole("Manager"));
}

<h2>Details</h2>

<div>
    <h4>Adoption</h4>
    <hr />
    <dl class="dl-horizontal">
        <div style="margin: 0 auto; width: 20%; font-size: 2em; display: flex; flex-direction: column; justify-content: center;">
            <dt>
                <span>Adoption Date</span>
            </dt>
            <dd style="padding-left: 15px;">
                @Html.DisplayFor(model => model.AdoptionDate)
            </dd>

        </div>
        <div style="display: flex; flex-direction: row; justify-content: space-between; margin: 0 auto; width: 60%; padding-top: 60px;">
            <div>
                <dt>
                    <span>Customer</span>
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Customer.Name)
                    @if (!string.IsNullOrWhiteSpace(Model.Customer.CustomerImage))
                    {
                        string url = Url.Content(
                           Constants.CUSTOMERS_FOLDER_PATH +
                           Model.Customer.CustomerImage);
                        <img src="@url" style="display: flex; justify-content: center;" />
                    }
                </dd>
            </div>
            <div>
                <dt>
                    <span>Dog</span>
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Dog.Name)
                    @if (!string.IsNullOrWhiteSpace(Model.Dog.DogImage))
                    {
                        string url = Url.Content(
                           Constants.DOGS_FOLDER_PATH +
                           Model.Dog.DogImage);
                        <img src="@url" style="display: flex; justify-content: center;" />
                    }
                </dd>
            </div>
        </div>

    </dl>
</div>
<p>
    @if (isManager)
    {
        @Html.ActionLink("Edit", "Edit", new { id = Model.CustomerId, dog = Model.DogId }) 
        <span>|</span>
    }
    @Html.ActionLink("Back to List", "Index")
</p>

Custom Lab/CustomLab/DogAdoption.Website/Views/Adoptions/Index.cshtml
@model DogAdoption.Website.ViewModels.AdoptionSearchResults

@using PagedList.Mvc

@{
    ViewBag.Title = "Index";

    bool isManager =
      Request.IsAuthenticated &&
      (User.IsInRole("Admin") || User.IsInRole("Manager"));

    bool isAuthorized =
      Request.IsAuthenticated &&
      (User.IsInRole("Admin") || User.IsInRole("Manager") || User.IsInRole("Counselor"));
}

<h2>Adoptions</h2>
@using (Html.BeginForm("Index", "Adoptions", FormMethod.Get,
    new { enctype = "multipart/form-data" }))
{

    var sortByArray = new SelectListItem[]
    {
new SelectListItem {Value = "date", Text = "Date"},
new SelectListItem {Value = "dogName", Text = "Dog Name"},
new SelectListItem {Value = "customerName", Text = "Customer Name"}
    };

    <div class="mb-3">
        @Html.EditorFor(m => m.Search, new { htmlAttributes = new { placeholder = "search" } })
        @Html.DropDownListFor(m => m.SortBy, sortByArray)

        <input class="btn btn-primary" type="submit" value="Apply" />
    </div>
}

@if (isAuthorized)
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}
<table class="table">
    <tr>
        <th>
            <span>Adoption Date</span>
        </th>
        <th>
            <span>Customer</span>
        </th>
        <th>
            <span>Dog</span>
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Adoptions)
    {
        <tr>
            <td>
                <span>@item.AdoptionDate.ToString("MM/dd/yyy")</span>
            </td>
            <td style="display: flex; flex-direction: column; justify-content: center;">
                <span style="padding-left: 20px;">
                    @Html.DisplayFor(modelItem => item.Customer.Name)
                    </span>
                    @if (!string.IsNullOrWhiteSpace(item.Customer.CustomerImage))
                    {
                        string url = Url.Content(
                           Constants.CUSTOMERS_FOLDER_PATH +
                           Constants.THUMBNAILS_FOLDER +
                           item.Customer.CustomerImage);
                        <img src="@url" width="50%" />
                    }
            </td>
            <td>
                <div style="display: flex; flex-direction: column; justify-content: center;">
                    <span style="padding-left: 30px;">
                        @Html.DisplayFor(modelItem => item.Dog.Name)
                    </span>
                    @if (!string.IsNullOrWhiteSpace(item.Dog.DogImage))
                    {
                        string url = Url.Content(
                           Constants.DOGS_FOLDER_PATH +
                           Constants.THUMBNAILS_FOLDER +
                           item.Dog.DogImage);
                        <img src="@url" width="50%"  style="display: flex; justify-content: center;"/>
                    }
                </div>
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.CustomerId, dog = item.DogId })
                @if (isManager)
                {
                    <span>|</span>
                    @Html.ActionLink("Delete", "Delete", new { id = item.CustomerId, dog = item.DogId })
                }
            </td>
        </tr>
    }

</table>
<div>
    @Html.PagedListPager(
    Model.Adoptions,
    page => Url.Action("Index", new
    {
        search = Model.Search,
        sortBy = Model.SortBy,
        page = page,
        itemsPerPage = Model.Adoptions.PageSize,
    }),
    new PagedListRenderOptions
    {
        Display = PagedListDisplayMode.IfNeeded,
        DisplayPageCountAndCurrentLocation = true,
        DisplayEllipsesWhenNotShowingAllPageNumbers = true,
        MaximumPageNumbersToDisplay = 5,
        PageCountAndCurrentLocationFormat = "Page {0} of {1}"
    })

</div>

@section scripts
{
    <script>
        $(".pagination > li").addClass("page-item");
        $(".pagination > li > a").addClass("page-link");
    </script>
}