Custom Lab/CustomLab/DogAdoption.Website/Models/Customer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DogAdoption.Website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Adoptions = new HashSet<Adoption>();
        }
    
        public int CustomerId { get; set; }
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
        public string AddressOne { get; set; }
        public string AddressTwo { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string CustomerImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adoption> Adoptions { get; set; }
    }
}

Custom Lab/CustomLab/DogAdoption.Website/Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using DogAdoption.Website.Models;
using DogAdoption.Website.ViewModels;
using NLog;
using PagedList;

namespace DogAdoption.Website.Controllers
{
    public class CustomersController : Controller
    {
        private DogAdoptionEntities1 db = new DogAdoptionEntities1();
        private Logger logger = LogManager.GetCurrentClassLogger();

        public bool ValidateImage(string name, HttpPostedFileBase file)
        {
            if (file == null)
            {
                ModelState.AddModelError(name, "Please select a file");
                return false;
            }

            if (file.ContentLength <= 0)
            {
                ModelState.AddModelError(name, "File size was zero");
                return false;
            }

            if (file.ContentLength >= Constants.MAX_UPLOAD_FILE_SIZE)
            {
                ModelState.AddModelError(name, "File size was to big");
                return false;
            }

            string fileExtension = Path.GetExtension(file.FileName).ToLower();
            if (!Constants.ALLOWED_IMAGE_EXTENSIONS.Contains(fileExtension))
            {
                ModelState.AddModelError(name, $"File extension {fileExtension} not allowed");
                return false;
            }

            return true;
        }

        private void UploadCustomerImage(Customer customer, HttpPostedFileBase file)
        {
            WebImage img = new WebImage(file.InputStream);
            if (img.Width > 350 || img.Height > 600)
            {
                img.Resize(350, 600);
            }

            string fileName = file.FileName.ToLower();
            img.Save(Constants.CUSTOMERS_FOLDER_PATH + fileName);
            
            img.Resize(100, 100);
            img.Save(Constants.CUSTOMERS_FOLDER_PATH + Constants.THUMBNAILS_FOLDER + fileName);
            
            customer.CustomerImage = fileName;
        }

        // GET: Customers
        [Authorize(Roles = "Admin, Manager, Counselor")]
        public ActionResult Index(
            string search,
            string sortBy,
            int? page,
            int? itemsPerPage)
        {
            IQueryable<Customer> cust =
                from c in db.Customers
                orderby c.CustomerId, c.Name
                select c;

            if (!String.IsNullOrWhiteSpace(search))
            {
                cust = cust.Where(
                       m => m.Name.Contains(search) ||
                       m.CustomerId.ToString().Contains(search)
                    );
            }

            switch (sortBy)
            {
                default:
                case "customerNumber":
                    cust = cust.OrderBy(m => m.CustomerId);
                    break;
                case "customerName":
                    cust = cust.OrderBy(m => m.Name);
                    break;
            }

            var model = new CustomerSearchResults()
            {
                Search = search,
                SortBy = sortBy,
                Customers = cust.ToPagedList(page ?? 1, itemsPerPage ?? 5)
            };

            return View("Index", model);
        }

        // GET: Customers/Details/5
        [Authorize(Roles = "Admin, Manager, Counselor")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            logger.Info($"{User.Identity.Name} viewed {customer.Name}");
            return View(customer);
        }

        // GET: Customers/Create
        [Authorize(Roles = "Admin, Manager, Counselor")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin, Manager, Counselor")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CustomerId,Name,PhoneNumber,AddressOne,AddressTwo,City,State,Zip,CustomerImage")]
        Customer customer,
             HttpPostedFileBase imageUpload)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (imageUpload != null &&
                        ValidateImage("CustomerImage", imageUpload))
                    {
                        UploadCustomerImage(customer, imageUpload);
                    }

                    db.Customers.Add(customer);
                    logger.Info($"{User.Identity.Name} created {customer.Name}");
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

            }
            catch(Exception ex)
            {
                logger.Error(ex, $"{User.Identity.Name} had an error creating {customer.Name}");
                ModelState.AddModelError("CustomerId", ex);
            }
            return View(customer);
        }

        // GET: Customers/Edit/5
        [Authorize(Roles = "Admin, Manager, Counselor")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Manager, Counselor")]
        public ActionResult Edit([Bind(Include = "CustomerId,Name,PhoneNumber,AddressOne,AddressTwo,City,State,Zip,CustomerImage")]
        Customer customer,
             HttpPostedFileBase imageUpload)
        {
            try
            { 
                if (imageUpload != null &&
                    ValidateImage("CustomerImage", imageUpload))
                {
                    UploadCustomerImage(customer, imageUpload);
                }

                if (ModelState.IsValid)
                {
                    db.Entry(customer).State = EntityState.Modified;
                    logger.Info($"{User.Identity.Name} modified {customer.Name}");
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                logger.Error(ex, $"{User.Identity.Name} had an error editing {customer.Name}");
                ModelState.AddModelError("CustomerId", ex);
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        [Authorize(Roles = "Admin, Manager")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Customer customer = db.Customers.Find(id);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        // POST: Customers/Delete/5
        [Authorize(Roles = "Admin, Manager")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            { 
            Customer customer = db.Customers.Find(id);
            db.Customers.Remove(customer);
            logger.Info($"{User.Identity.Name} deleted {customer.Name}");
            db.SaveChanges();
            }
            catch (Exception ex)
            {
                logger.Error(ex, $"{User.Identity.Name} had an error deleting {db.Customers.Find(id).Name}");
                ModelState.AddModelError("CustomerId", ex);
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Custom Lab/CustomLab/DogAdoption.Website/Views/Customers/Create.cshtml
@model DogAdoption.Website.Models.Customer

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Customers", FormMethod.Post,
    new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Customer</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <span>Phone Number</span>
        <div class="col-md-10">
            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <span>Address</span>
        <div class="col-md-10">
            @Html.EditorFor(model => model.AddressOne, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AddressOne, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <span>Apt. #</span>
        <div class="col-md-10">
            @Html.EditorFor(model => model.AddressTwo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AddressTwo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <span>Image</span>
        <div class="col-md-10">
            @Html.EditorFor(model => model.CustomerImage, new { htmlAttributes = new { @class = "form-control", list = "images" } })
            <input type="file" name="imageUpload" class="form-control-file" />
            @Html.ValidationMessageFor(model => model.CustomerImage, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Custom Lab/CustomLab/DogAdoption.Website/Views/Customers/Delete.cshtml
@model DogAdoption.Website.Models.Customer

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            <span>Phone Number</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            <span>Address</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressOne)
        </dd>

        @if (!string.IsNullOrWhiteSpace(Model.AddressTwo))
        {
            <dt>
                <span>Apt. #</span>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AddressTwo)
            </dd>
        }

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zip)
        </dd>

        <dt>
            <span>Image</span>
        </dt>

        <dd>
            @if (!string.IsNullOrWhiteSpace(Model.CustomerImage))
            {
                string url = Url.Content(
                   Constants.CUSTOMERS_FOLDER_PATH +
                   Model.CustomerImage);
                <img src="@url" />
            }
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Custom Lab/CustomLab/DogAdoption.Website/Views/Customers/Details.cshtml
@model DogAdoption.Website.Models.Customer

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Customer</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            <span>Phone Number</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>

        <dt>
            <span>Address</span>
        </dt>

        <dd>
            @Html.DisplayFor(model => model.AddressOne)
        </dd>

        @if (!string.IsNullOrWhiteSpace(Model.AddressTwo))
        {
            <dt>
                <span>Apt. #</span>
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AddressTwo)
            </dd>
        }

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Zip)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Zip)
        </dd>

        <dt>
            <span>Image</span>
        </dt>

        <dd>
            @if (!string.IsNullOrWhiteSpace(Model.CustomerImage))
            {
                string url = Url.Content(
                   Constants.CUSTOMERS_FOLDER_PATH +
                   Model.CustomerImage);
                <img src="@url" />
            }
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CustomerId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Custom Lab/CustomLab/DogAdoption.Website/Views/Customers/Edit.cshtml
@model DogAdoption.Website.Models.Customer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Customers", FormMethod.Post,
    new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Customer</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.CustomerId)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <span>Phone Number</span>
        <div class="col-md-10">
            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <span>Address</span>
        <div class="col-md-10">
            @Html.EditorFor(model => model.AddressOne, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AddressOne, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <span>Apt. #</span>
        <div class="col-md-10">
            @Html.EditorFor(model => model.AddressTwo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AddressTwo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Zip, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Zip, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Zip, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        <span>Image</span>
        <div class="col-md-10">
            @Html.EditorFor(model => model.CustomerImage, new { htmlAttributes = new { @class = "form-control", list = "images" } })
            <input type="file" name="imageUpload" class="form-control-file" />
            @Html.ValidationMessageFor(model => model.CustomerImage, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Custom Lab/CustomLab/DogAdoption.Website/Views/Customers/Index.cshtml
@model DogAdoption.Website.ViewModels.CustomerSearchResults

@using PagedList.Mvc

@{
    ViewBag.Title = "Customers";


    bool isManager =
      Request.IsAuthenticated &&
      (User.IsInRole("Admin") || User.IsInRole("Manager"));
    
}

<h2>Customers</h2>

@using (Html.BeginForm("Index", "Customers", FormMethod.Get,
    new { enctype = "multipart/form-data" }))
{

    var sortByArray = new SelectListItem[]
    {
new SelectListItem {Value = "customerNumber", Text = "Customer Number"},
new SelectListItem {Value = "customerName", Text = "Customer Name"}
    };

    <div class="mb-3">
        @Html.EditorFor(m => m.Search, new { htmlAttributes = new { placeholder = "search" } })
        @Html.DropDownListFor(m => m.SortBy, sortByArray)

        <input class="btn btn-primary" type="submit" value="Apply" />
    </div>
}

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Name
        </th>
        <th>
            Phone Number
        </th>
        <th>
            Address
        </th>
        <th>
            Apt. #
        </th>
        <th>
            City
        </th>
        <th>
            State
        </th>
        <th>
            Zip
        </th>
        <th>
            Image
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.Customers)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AddressOne)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AddressTwo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Zip)
            </td>
            <td>
                @if (!string.IsNullOrWhiteSpace(item.CustomerImage))
                {
                    string url = Url.Content(
                       Constants.CUSTOMERS_FOLDER_PATH +
                       Constants.THUMBNAILS_FOLDER +
                       item.CustomerImage);
                    <img src="@url" />
                }
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.CustomerId }) |
                @Html.ActionLink("Details", "Details", new { id = item.CustomerId })
                @if (isManager)
                {
                    <span>|</span>
                    @Html.ActionLink("Delete", "Delete", new { id = item.CustomerId })
                }

            </td>
        </tr>
    }

</table>

<div>
    @Html.PagedListPager(
    Model.Customers,
    page => Url.Action("Index", new
    {
        search = Model.Search,
        sortBy = Model.SortBy,
        page = page,
        itemsPerPage = Model.Customers.PageSize,
    }),
    new PagedListRenderOptions
    {
        Display = PagedListDisplayMode.IfNeeded,
        DisplayPageCountAndCurrentLocation = true,
        DisplayEllipsesWhenNotShowingAllPageNumbers = true,
        MaximumPageNumbersToDisplay = 5,
        PageCountAndCurrentLocationFormat = "Page {0} of {1}"
    })

</div>

@section scripts
{
    <script>
        $(".pagination > li").addClass("page-item");
        $(".pagination > li > a").addClass("page-link");
    </script>
}