Movies/LB01/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;

namespace LB01.Models
{
    [Table("Movies")]
    public class Movie
    {
        [Key]
        [Display(Name = "ID")]
        [Required(ErrorMessage = "Movie ID is required.")]
        public int MovieId { get; set; }

        [Display(Name = "Name")]
        [Required(ErrorMessage = "Movie name is required.")]
        [MinLength(3, ErrorMessage = "The name must be at least 3 characters long.")]
        [StringLength(200, ErrorMessage = "The name cannot exceed 200 characters.")]
        public string MovieName { get; set; }

        [Display(Name = "Description")]
        [Required(ErrorMessage = "Movie description is required.")]
        [MinLength(3, ErrorMessage = "The description must be at least 3 characters long.")]
        [DataType(DataType.MultilineText)]
        public string MovieDescription { get; set; }

        [Display(Name = "Image")]
        [StringLength(200, ErrorMessage = "The image name cannot exceed 200 characters.")]
        public string MovieImage { get; set; }

        [Display(Name = "Released")]
        [Required(ErrorMessage = "Release year is required.")]
        [Range(1900, 2100, ErrorMessage = "The release year must be between {1} and {2}.")]
        public int ReleasedYear { get; set; }

        [Display(Name = "Ticket Sales")]
        [DisplayFormat(DataFormatString = "{0:0,,,.0} B")]
        [Range(0, 100000000000, ErrorMessage = "Ticket sales must be between {1} and {2}.")]
        [DataType(DataType.Currency)]
        public decimal? TicketSales { get; set; }

        [Display(Name = "Genre")]
        [Required(ErrorMessage = "Genre is required.")]
        public byte GenreId { get; set; }
        public virtual Genre Genre { get; set; }

        [Display(Name = "Cast")]
        public virtual ICollection<Actor> Cast { get; set; }

        [Display(Name = "Ratings")]
        public virtual IList<MovieRating> CustomerRatings { get; set; }

        [NotMapped]
        [Display(Name = "Rating")]
        public double AverageRating
        {
            get
            {
                if (CustomerRatings.Any())
                {
                    return CustomerRatings.Average(x => x.Rating);
                    //for (int i = 0; i < CustomerRatings.Count; ++i)
                    //{
                    //    r += CustomerRatings[i].Rating;
                    //};

                    //return r / CustomerRatings.Count;
                }
                else
                {
                    return 0;
                }
            }
        }
    }
}

Movies/LB01/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using LB01.Models;
using LB01.ViewModels;
using Microsoft.AspNet.Identity;
using NLog;
using PagedList;

namespace LB01.Controllers
{
    public class MovieController : Controller
    {
        private MovieDatabase db = new MovieDatabase();
        private Logger logger = LogManager.GetCurrentClassLogger();

        // GET: Movie
        [AllowAnonymous]
        public ActionResult Index(
            string search,
            int? genreId,
            int? minYear,
            int? maxYear,
            string sortBy,
            int? page,
            int? itemsPerPage)
        {
            IQueryable<Movie> movies = db.Movies.Include("Genre");

            // Filter the results
            if (genreId != null)
            {
                movies = movies.Where(m => m.GenreId == genreId);
            }
            if (minYear != null)
            {
                movies = movies.Where(m => m.ReleasedYear >= minYear);
            }
            if (maxYear != null)
            {
                movies = movies.Where(m => m.ReleasedYear <= maxYear);
            }

            // Search by keyword
            if (!String.IsNullOrWhiteSpace(search))
            {
                movies = movies.Where(
                    m => m.MovieName.Contains(search) ||
                         m.MovieDescription.Contains(search) ||
                         m.ReleasedYear.ToString().Contains(search) ||
                         m.Genre.GenreName.Contains(search)
                );
            }

            // Sort the results
            switch (sortBy)
            {
                default:
                case "name":
                    movies = movies.OrderBy(m => m.MovieName);
                    break;
                case "year":
                    movies = movies.OrderBy(m => m.ReleasedYear).ThenBy(m => m.MovieName);
                    break;
                case "genre":
                    movies = movies.OrderBy(m => m.Genre.GenreName).ThenBy(m => m.MovieName);
                    break;
            }

            // Display the results
            var model = new MovieSearchResults
            {
                Search = search,
                GenreId = genreId,
                MinYear = minYear,
                MaxYear = maxYear,
                SortBy = sortBy,
                Genres = db.Genres.OrderBy(g => g.GenreName).ToList(),
                Results = movies.ToPagedList(page ?? 1, itemsPerPage ?? Constants.ITEMS_PER_PAGE),
            };

            return View("Index", model);
        }

        // GET: Movie/Details/5
        [AllowAnonymous]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            movie.Cast = movie.Cast.OrderBy(x => x.ActorId).ToList();

            MovieRating movieRating = db.MovieRatings.Find(movie.MovieId, User.Identity.GetUserId());
            MovieRatingEdit model = new MovieRatingEdit()
            {
                MovieId = movie.MovieId,
                MovieName = movie.MovieName,
                MovieDescription = movie.MovieName,
                MovieImage = movie.MovieImage,
                ReleasedYear = movie.ReleasedYear,
                TicketSales = movie.TicketSales,
                GenreId = movie.GenreId,
                Genre = movie.Genre,
                Cast = movie.Cast,
                CustomerRatings = movie.CustomerRatings,
                MovieRating = 0
            };

            if (movieRating != null)
            {
                model.MovieRating = movieRating.Rating;
            }

            logger.Info($"{User.Identity.GetUserName()} viewed {movie.MovieName}");
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Reviewer")]
        public ActionResult AddingRating(int? movieId, byte? movieRating)
        {
            string userId = User.Identity.GetUserId();
            MovieRating thisRate = db.MovieRatings.Find(movieId, userId);


            if (ModelState.IsValid)
            {
                if (!string.IsNullOrWhiteSpace(userId)
                    && movieRating != null &&
                    movieId != null
                    )
                {

                    if (thisRate != null)
                    {
                        thisRate.Rating = (byte)movieRating;
                    }
                    else
                    {
                        MovieRating movieRate = new MovieRating()
                        {
                            MovieId = (int)movieId,
                            UserId = userId,
                            Rating = (byte)movieRating
                        };


                        db.MovieRatings.Add(movieRate);
                    }
                    db.SaveChanges();
                }
            }
            return RedirectToAction("Details", new { id = movieId });
        }

        // GET: Movie/Create
        [Authorize(Roles = "Admin,Author")]
        public ActionResult Create()
        {
            MovieEditModel viewModel = new MovieEditModel();

            // Build an empty cast list
            viewModel.Cast = new List<ActorEditModel>();
            for (int i = 0; i < Constants.MAX_CAST_SIZE; ++i)
            {
                viewModel.Cast.Add(new ActorEditModel());
            }

            viewModel.ReleasedYear = DateTime.Now.Year;
            PopulateDropDowns(viewModel);
            return View(viewModel);
        }

        // POST: Movie/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin,Author")]
        public ActionResult Create(MovieEditModel viewModel)
        {
            try
            {
                Movie movieToCreate = new Movie()
                {
                    MovieId = viewModel.MovieId,
                    MovieName = viewModel.MovieName,
                    MovieDescription = viewModel.MovieDescription,
                    MovieImage = viewModel.MovieImage,
                    ReleasedYear = viewModel.ReleasedYear,
                    TicketSales = viewModel.TicketSales,
                    GenreId = viewModel.GenreId
                };
                db.Movies.Add(movieToCreate);

                // Add actors to the cast
                var cast = viewModel.Cast.Where(
                    x => !string.IsNullOrWhiteSpace(x.ActorName) ||
                            !string.IsNullOrWhiteSpace(x.ActorRole) ||
                            !string.IsNullOrWhiteSpace(x.ActorImage)
                ).ToList();
                for (int i = 0; i < Constants.MAX_CAST_SIZE && i < cast.Count; ++i)
                {
                    if (ValidateActor(cast, i))
                    {
                        var actorViewModel = cast[i];
                        var actor = new Actor();
                        actor.ActorName = actorViewModel.ActorName;
                        actor.ActorRole = actorViewModel.ActorRole;
                        actor.ActorImage = actorViewModel.ActorImage;
                        actor.Movie = movieToCreate;
                        db.Actors.Add(actor);
                    }
                }

                // Only save the movie if everything is valid
                if (ModelState.IsValid)
                {
                    // Upload the movie image if needed
                    UploadMovieImage(viewModel);
                    // Upload the actor images
                    UploadActorImages(cast);

                    // Save the movie to the database and display it if the images where uploaded successfully
                    if (ModelState.IsValid)
                    {
                        logger.Info($"{User.Identity.GetUserName()} created {movieToCreate.MovieName}");
                        db.SaveChanges();
                        return RedirectToAction("Details", new { id = movieToCreate.MovieId });
                    }
                }
            }
            catch(Exception ex)
            {
                logger.Error(ex, $"{User.Identity.GetUserName()} had an error creating {viewModel.MovieName}");
                ModelState.AddModelError("MovieName", ex);
                //return new HttpStatusCodeResult(500);
            }

            PopulateDropDowns(viewModel);
            return View(viewModel);
        }

        // GET: Movie/Edit/5
        [Authorize(Roles = "Admin,Author")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }

            MovieEditModel viewModel = new MovieEditModel()
            {
                MovieId = movie.MovieId,
                MovieName = movie.MovieName,
                MovieDescription = movie.MovieDescription,
                MovieImage = movie.MovieImage,
                ReleasedYear = movie.ReleasedYear,
                TicketSales = movie.TicketSales,
                GenreId = movie.GenreId
            };

            // Load the current cast
            viewModel.Cast = (
                from a in db.Actors
                where a.MovieId == movie.MovieId
                orderby a.ActorId

Movies/LB01/Views/Movie/Create.cshtml
@model LB01.ViewModels.MovieEditModel

@{
    ViewBag.Title = "Create Movie";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Create", "Movie", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.Partial("_MovieEditPartial", Model)

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/image_upload.js")
}

Movies/LB01/Views/Movie/Delete.cshtml
@model LB01.Models.Movie

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this movie?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.MovieName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MovieName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MovieDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MovieDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleasedYear)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleasedYear)
        </dd>

        @if (Model.TicketSales != null)
        {
            <dt>
                @Html.DisplayNameFor(model => model.TicketSales)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.TicketSales)
            </dd>
        }

        <dt>
            Genre
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Genre.GenreName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Movies/LB01/Views/Movie/Details.cshtml
@model LB01.ViewModels.MovieRatingEdit

@{
    ViewBag.Title = "Details";

    bool isAuthor =
        Request.IsAuthenticated &&
        (User.IsInRole("Admin") || User.IsInRole("Auther"));

    bool isReviewer =
        Request.IsAuthenticated &&
        (User.IsInRole("Reviewer"));


}

<div class="row col-md-12">
    @if (!String.IsNullOrWhiteSpace(Model.MovieImage))
    {
        <div class="col-md-6 mb-3">
            <img src="@Url.Content(Constants.MOVIE_IMAGE_PATH + Model.MovieImage)" 
                 alt="@Model.MovieName"
                 class="center"/>
        </div>
    }

        <div class="col-md-6 mb-3">
            <h2>@Html.DisplayFor(model => model.MovieName)</h2>
            <div class="mb-3">@Html.DisplayFor(model => model.MovieDescription)</div>
            <div>@String.Format("Released in {0}", Model.ReleasedYear)</div>
            <div>@String.Format("Ticket Sales: {0:C}", Model.TicketSales)</div>
            <div>@String.Format("Genre: {0}", Model.Genre.GenreName)</div>

            <div style="display: flex; justify-content: space-between; flex-direction: row;">
                <p>Average Rating:</p>
                @{ double avgRating = Model.AverageRating; }
                @if (avgRating > 4.75d)
                {
                    <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i>
                }
                else if (avgRating > 4.25)
                {
                    <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-a"></i><i class="fas fa-star-half-alt"></i>
                }
                else if (avgRating > 3.75)
                {
                    <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i>
                }
                else if (avgRating > 3.25)
                {
                    <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i><i class="far fa-star"></i>
                }
                else if (avgRating > 2.75)
                {
                    <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
                }
                else if (avgRating > 2.25)
                {
                    <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i><i class="far fa-star"></i><i class="far fa-star"></i>
                }
                else if (avgRating > 1.75)
                {
                    <i class="fas fa-star"></i><i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
                }
                else if (avgRating > 1.25)
                {
                    <i class="fas fa-star"></i><i class="fas fa-star-half-alt"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
                }
                else if (avgRating > .75)
                {
                    <i class="fas fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
                }
                else if (avgRating > .25)
                {
                    <i class="fas fa-star-half-alt"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i><i class="far fa-star"></i>
                }
                else if (avgRating < .25)
                {
                    <i class="far fa-star"></i> <i class="far fa-star"></i> <i class="far fa-star"></i> <i class="far fa-star"></i> <i class="far fa-star"></i>
                }
            </div>

            @if (isReviewer)
            {
                using (Html.BeginForm("AddingRating", "Movie", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div style="display: flex; justify-content: flex-start;">
                        <p>Your Rating:</p>
                        @Html.HiddenFor(m => m.MovieId)
                        @Html.EditorFor(m => m.MovieRating)
                        <input type="submit" value="Submit" class="btn btn-default" />
                    </div>
                }
            }

            @if (Model.Cast.Any())
            {
                <h4>Cast</h4>
                foreach (var actor in Model.Cast)
                {
                    <div class="m-2">
                        <img src="@Url.Content(Constants.ACTOR_IMAGE_PATH + actor.ActorImage)"
                             alt="@actor.ActorName" />
                        <span>@actor.ActorName</span>
                        <span>(@actor.ActorRole)</span>
                    </div>
                }
            }

        </div>
</div>

<p>
    @if (isAuthor)
    {
    <span>@Html.ActionLink("Edit", "Edit", new { id = Model.MovieId }) |</span> 
    }
    @Html.ActionLink("Back to List", "Index")
</p>

Movies/LB01/Views/Movie/Edit.cshtml
@model LB01.ViewModels.MovieEditModel

@{
    ViewBag.Title = "Edit Movie";
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Edit", "Movie", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.Partial("_MovieEditPartial", Model)

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
}

<div>
    @Html.ActionLink("View", "Details", new { id = Model.MovieId }) |
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/image_upload.js")
}

Movies/LB01/Views/Movie/Index.cshtml
@model LB01.ViewModels.MovieSearchResults
@using PagedList.Mvc;

@{
    ViewBag.Title = "Movies";

    bool isAuthor =
        Request.IsAuthenticated &&
        (User.IsInRole("Admin") || User.IsInRole("Auther"));
}

<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("Index", "Movie", FormMethod.Get))
{
    var genres = new SelectList(Model.Genres, "GenreId", "GenreName");
    var sortByArray = new SelectListItem[]
    {
        new SelectListItem { Value = "name", Text = "Name" },
        new SelectListItem { Value = "year", Text = "Year" },
        new SelectListItem { Value = "genre", Text = "Genre" },
    };
    var sortByList = new SelectList(sortByArray, "Value", "Text");

    <div class="card text-white bg-secondary mb-3">
        <div class="card-header">Filters</div>
        <div class="card-body form-group row">
            <div class="col-md-3">
                @Html.HiddenFor(x => x.Search)
                @Html.LabelFor(x => x.GenreId)
                @Html.DropDownListFor(x => x.GenreId, genres, "(All)", htmlAttributes: new { @class = "form-control input-sm" })
            </div>
            <div class="col-md-4">
                <label for="MinYear">Release Year</label>
                <div class="row">
                    <div class="col-md-6">
                        @Html.EditorFor(x => x.MinYear, new { htmlAttributes = new { @class = "form-control input-sm", placeholder = "min" } })
                    </div>
                    <div class="col-md-6">
                        @Html.EditorFor(x => x.MaxYear, new { htmlAttributes = new { @class = "form-control input-sm", placeholder = "max" } })
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <label for="SortBy">Sort By</label>
                @Html.DropDownListFor(x => x.SortBy, sortByList, htmlAttributes: new { @class = "form-control input-sm" })
            </div>
            <div class="col-md-1">
                <label>&nbsp;</label>
                <input class="btn btn-primary align-bottom" type="submit" value="Apply" />
            </div>
        </div>
    </div>
}

<table class="movie-list table">
    <tr class="bg-secondary">
        <th>Name</th>
        <th>Year</th>
        <th>Ticket Sales</th>
        <th>Genre</th>
        <th></th>
    </tr>

    @foreach (var item in Model.Results)
    {
    <tr>
        <td>
            <a href="@Url.Action("Details", new { id = item.MovieId })">
                @Html.DisplayFor(x => item.MovieName)
            </a>
        </td>
        <td>
            @Html.DisplayFor(x => item.ReleasedYear)
        </td>
        <td>
            @Html.DisplayFor(x => item.TicketSales)
        </td>
        <td>
            @Html.DisplayFor(x => item.Genre.GenreName)
        </td>
        @if (isAuthor)
        {
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.MovieId }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.MovieId })
            </td>
        }
        else
        {
            <td></td>
        }
        </tr>
    }

</table>
@if (isAuthor) {
<div class="float-right">
    @Html.ActionLink("Create Movie", "Create", null, new { @class = "btn btn-outline-primary" })
</div>
}
<div>
    @Html.PagedListPager(
        Model.Results,
        page => Url.Action("Index", new
        {
            Search = Model.Search,
            GenreId = Model.GenreId,
            MinYear = Model.MinYear,
            MaxYear = Model.MaxYear,
            SortBy = Model.SortBy,
            Page = page,
            ItemsPerPage = Model.Results.PageSize,
        }),
        new PagedListRenderOptions {
            Display = PagedListDisplayMode.IfNeeded,
            DisplayPageCountAndCurrentLocation = true,
            DisplayEllipsesWhenNotShowingAllPageNumbers = true,
            MaximumPageNumbersToDisplay = 5,
            PageCountAndCurrentLocationFormat = "Page {0} of {1}"
        }
    )
</div>

@section scripts
{
    <script>
        $(".pagination > li").addClass("page-item");
        $(".pagination > li > a").addClass("page-link");
    </script>
}